Pizzeria_Project/pizzas/urls.py
from django.urls import path

from . import views

app_name = 'pizzas'

urlpatterns = [
    path('',views.index, name='index'),
    path('pizzas', views.pizzas, name='pizzas'),
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
    path('new_pizza/',views.new_pizza, name='new_pizza'),
    path('new_topping/<int:pizza_id>/',views.new_topping, name='new_topping'),
    path('edit_topping/<int:topping_id>/',views.edit_topping, name='edit_topping'),
    path('comments/<int:pizza_id>/', views.comments, name='comments')
]

Pizzeria_Project/pizzas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Pizza(models.Model):
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    #image = models.ImageField(upload_to='images',blank=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

Pizzeria_Project/pizzas/forms.py
from django import forms
from .models import Pizza, Topping, Comment

class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ['name']
        labels = {'Name': ''}

class ToppingForm(forms.ModelForm):
    class Meta:
        model = Topping
        fields = ['name']
        labels = {'Name': ''}

#Might not use
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name']
        labels = {'Name': ''}

Pizzeria_Project/pizzas/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Pizza, Topping, Comment
from .forms import PizzaForm, ToppingForm, CommentForm
from django.http import Http404
# Create your views here.

def index(request):
    ''' The home page for Pizzeria '''
    return render(request, 'pizzas/index.html')

@login_required
def pizzas(request):
    pizzas = Pizza.objects.filter(owner=request.user).order_by('date_added')
    context = {'pizzas':pizzas}
    return render(request, 'pizzas/pizzas.html', context)

@login_required
def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('-date_added')
    if pizza.owner != request.user:
        raise Http404
    context = {'pizza':pizza, 'toppings':toppings}
    return render(request, 'pizzas/pizza.html', context)

@login_required
def new_pizza(request):
    if request.method != 'POST':
        form = PizzaForm()
    else:
        form = PizzaForm(data=request.POST)
        if form.is_valid():
            new_pizza = form.save(commit=False)
            new_pizza.owner = request.user
            new_pizza.save()
            
            return redirect('pizzas:pizzas')
    context = {'form':form}
    return render(request, 'pizzas/new_pizza.html', context)

@login_required
def new_topping(request,pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    if pizza.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = ToppingForm()
    else:
        form = ToppingForm(data=request.POST)
        if form.is_valid():
            new_topping = form.save(commit=False)
            new_topping.pizza = pizza
            new_topping.save()
            return redirect('pizzas:pizza', pizza_id=pizza_id)
    context = {'form':form, 'pizza':pizza}  #passing pizza because we want to see the pizza, not the number that represents its id
    return render(request, 'pizzas/new_topping.html', context)

@login_required
def edit_topping(request,topping_id):
    topping = Topping.objects.get(id=topping_id)
    pizza = topping.pizza
    if pizza.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = ToppingForm(instance=topping)
    else:
        form = ToppingForm(instance=topping, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('pizzas:pizza',pizza_id=pizza.id)
    context = {'topping':topping, 'pizza':pizza, 'form':form}
    return render(request, 'pizzas/edit_topping.html', context)

@login_required
def comments(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    comments = Comment.object.filter(id=pizza_id)
    if request.method != 'POST':
        form = CommentForm()
    else:
        form = CommentForm(data=request.POST)
        if form.is_valid():
            comments = form.save(commit=False)
            comments.pizza = pizza
            comments.owner = request.user
            comments.save()
            return redirect('pizzas:pizza',pizza_id=pizza_id)
    context = {'pizza':pizza, 'comments':comments}
    return render(request, 'pizzas/comments.html', context) 

    '''
    if request.method == 'POST' and request.POST.get("btn1"):
        comment = request.POST.get("comment")
        Comment.objects.create(pizza_id=pizza_id,name=comment,date_added=date.today())
    comments = Comment.object.filter(pizza=pizza_id)
    pizza = Pizza.objects.get(id=pizza_id)

    context = {'pizza':pizza, 'comments':comments}
    return render(request, 'pizzas/comments.html', context)
    '''

Pizzeria_Project/pizzas/templates/pizzas/base.html
{% load bootstrap4 %}

<!doctype html>

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
          shrink-to-fit=no">
    <title>Pizzeria</title>

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}

</head>

<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

        <a class="navbar-brand" href="{% url 'pizzas:index' %}">Justin's Pizzeria Home</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav item">
                    <a class="nav-link" href="{% url 'pizzas:pizzas' %}">Pizzas</a>
                </li>
            </ul>

            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}

                <li class="nav-item">
                    <span class="navbar-text">Hello, {{ user.username }}.</span>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                </li>

                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                </li>
                {% endif %}
            </ul>
        </div>

    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>

        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>




</html>

Pizzeria_Project/pizzas/templates/pizzas/comments.html
{% extends "pizzas/base.html" %}
{% load bootstrap4 %}

{% block content %}
<p> <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a> </p>

<p> Comment on this Pizza: </p>

<form action="{% url 'pizzas:comments' pizza.id %}" method='post'>

    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit" class="btn btn-outline-primary">Add Comment</button>
</form>

{% endblock content %}

Pizzeria_Project/pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}


{% block page_header %}
<div class="jumbotron">
    <h1 class="display-3">Welcome to Justin's Pizzeria</h1>
    <p class="lead">Choose or Make a Pizza.
    </p>

    <a class="btn btn-lg btn-outline-primary" href="{% url 'users:register' %}" role="button">Create an account
        &raquo;</a>
</div>
{% endblock page_header %}

Pizzeria_Project/pizzas/templates/pizzas/new_pizza.html
{% extends "pizzas/base.html" %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}

{% block content %}

<p> Add a new Pizza: </p>

<form action="{% url 'pizzas:new_pizza' %}" method='post'>

    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit" class="btn btn-outline-primary">Add Pizza</button>

</form>

{% endblock content %}

Pizzeria_Project/pizzas/templates/pizzas/new_topping.html
{% extends "pizzas/base.html" %}
{% load bootstrap4 %}
{% load crispy_forms_tags %}

{% block content %}
<p> <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a> </p>

<!--pizza.id is used here instead of pizza_id because we are referring to the ATTRIBUTE (id) OF THE OBJECT (pizza), not the variable associated with pizza used in views-->

<p> Add a new topping: </p>

<form action="{% url 'pizzas:new_topping' pizza.id %}" method='post'>

    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit" class="btn btn-outline-primary">Add Topping</button>
</form>

{% endblock content %}

Pizzeria_Project/pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}
{% load bootstrap4 %}

{% block content %}

<p> Pizza: {{ pizza.name }} </p>

<ul>
    {% for topping in toppings %}
    <li>
        <p>{{topping.name | linebreaks}}</p>
    </li>
    <p>
        <a href="{% url 'pizzas:edit_topping' topping.id %}">Edit Topping</a>
    </p>
    {% empty %}
    <li>Toppings for this pizza have not been added yet</li>
    {% endfor %}
</ul>

<p> <a href="{% url 'pizzas:new_topping' pizza.id %}">Add a new Topping</a> </p>

<ul>
    {% for comment in comments %}
    <li>
        <p>{{comment.name | linebreaks}}</p>
    </li>
    {% empty %}
    <li>There are no comments for this Pizza</li>
    {% endfor %}
</ul>
<p>
    <a href="{% url 'pizzas:comments' pizza.id %}">Add a comment to this Pizza</a>

</p>

{% endblock content %}

Pizzeria_Project/pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}


{% block content %}

<p> Pizzas </p>

<ul>
    <p>
        <img src="https://www.nicepng.com/png/detail/812-8126235_hawaiian-pizza-png.png" class="img-thumbnail"
            style="max-height:300px" alt="">
    </p>
    <p>
        <img src="https://napolipizzalv.com/wp-content/uploads/2019/10/DSC_0956-min.png" class="img-thumbnail"
            style="max-height:300px" alt="">
    </p>
    {% for pizza in pizzas %}

    <li>
        <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
    </li>
    {% empty %}
    <li> No pizzas have been added yet.</li>

    {% endfor %}
</ul>

<a href="{% url 'pizzas:new_pizza' %}">Add a new Pizza</a>

{% endblock content %}