Pizza_final/Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
    path('users/', include('users.urls')),
]

Pizza_final/pizzas/urls.py
from django.urls import path

from . import views

app_name = 'pizzas'

urlpatterns = [
    path('',views.index, name='index'),
    path('pizzas', views.pizzas, name='pizzas'),
    path('pizzas/<int:pizza_id>/', views.pizza, name='pizza'),
    path('new_pizza/',views.new_pizza, name='new_pizza'),
    path('new_topping/<int:pizza_id>/',views.new_topping, name='new_topping'),
    path('edit_topping/<int:topping_id>/',views.edit_topping, name='edit_topping'),
]

Pizza_final/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('',include('django.contrib.auth.urls')),
    path('register/',views.register,name='register')
]

Pizza_final/pizzas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Pizza(models.Model):
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Comment(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

Pizza_final/users/models.py
from django.db import models

# Create your models here.

Pizza_final/pizzas/forms.py
from django import forms
from .models import Pizza, Topping

class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ['name']
        labels = {'Name': ''}

class ToppingForm(forms.ModelForm):
    class Meta:
        model = Topping
        fields = ['name']
        labels = {'Name': ''}

Pizza_final/pizzas/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Pizza, Topping
from .forms import PizzaForm, ToppingForm
from django.http import Http404
# Create your views here.

def index(request):
    ''' The home page for Pizzeria '''
    return render(request, 'pizzas/index.html')

@login_required
def pizzas(request):
    pizzas = Pizza.objects.filter(owner=request.user).order_by('date_added')
    context = {'pizzas':pizzas}
    return render(request, 'pizzas/pizzas.html', context)

@login_required
def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('-date_added')
    if pizza.owner != request.user:
        raise Http404
    context = {'pizza':pizza, 'toppings':toppings}
    return render(request, 'pizzas/pizza.html', context)

@login_required
def new_pizza(request):
    if request.method != 'POST':
        form = PizzaForm()
    else:
        form = PizzaForm(data=request.POST)
        if form.is_valid():
            new_pizza = form.save(commit=False)
            new_pizza.owner = request.user
            new_pizza.save()
            
            return redirect('pizzas:pizzas')
    context = {'form':form}
    return render(request, 'pizzas/new_pizza.html', context)

@login_required
def new_topping(request,pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    if pizza.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = ToppingForm()
    else:
        form = ToppingForm(data=request.POST)
        if form.is_valid():
            new_topping = form.save(commit=False)
            new_topping.pizza = pizza
            new_topping.save()
            return redirect('pizzas:pizza', pizza_id=pizza_id)
    context = {'form':form, 'pizza':pizza}  #passing pizza because we want to see the pizza, not the number that represents its id
    return render(request, 'pizzas/new_topping.html', context)

@login_required
def edit_topping(request,topping_id):
    topping = Topping.objects.get(id=topping_id)
    pizza = topping.pizza
    if pizza.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = ToppingForm(instance=topping)
    else:
        form = ToppingForm(instance=topping, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('pizzas:pizza',pizza_id=pizza.id)
    context = {'topping':topping, 'pizza':pizza, 'form':form}
    return render(request, 'pizzas/edit_topping.html', context)

Pizza_final/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request,new_user)
            return redirect('pizzas:index')

    context = {'form':form}
    return render(request,'registration/register.html', context)

Pizza_final/pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Justin's Pizzeria Home</a>
    <li class="nav item">
        <a class="nav-link" href="{% url 'pizzas:pizzas' %}">Pizzas</a>
    </li>

    {% if user.is_authenticated %}
    Hello, {{user.username}}.
    <li class="nav item">
        <a class="nav-link" href="{% url 'users:logout' %}">Log Out</a>
    </li>
    {% else %}
    <li class="nav item">
        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
    </li>
    <li class="nav item">
        <a class="nav-link" href="{% url 'users:login' %}">Log In</a>
    </li>
    {% endif %}

</p>

{% block content %}{% endblock content %}

Pizza_final/pizzas/templates/pizzas/edit_topping.html
{% extends "pizzas/base.html" %}


{% block content %}
<p> <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a> </p>

<p> Edit your toppings: </p>

<form action="{% url 'pizzas:edit_topping' topping.id %}" method='post'>

    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">Save Changes</button>
</form>

{% endblock content %}

Pizza_final/pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}


{% block content %}

<p> Welcome to Justin's Pizzeria! Make a Pizza! </p>

{% endblock content %}

Pizza_final/pizzas/templates/pizzas/new_pizza.html
{% extends "pizzas/base.html" %}


{% block content %}

<p> Add a new Pizza: </p>

<form action="{% url 'pizzas:new_pizza' %}" method='post'>

    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">Add Pizza</button>

</form>

{% endblock content %}

Pizza_final/pizzas/templates/pizzas/new_topping.html
{% extends "pizzas/base.html" %}


{% block content %}
<p> <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a> </p>

<!--pizza.id is used here instead of pizza_id because we are referring to the ATTRIBUTE (id) OF THE OBJECT (pizza), not the variable associated with pizza used in views-->

<p> Add a new topping: </p>

<form action="{% url 'pizzas:new_topping' pizza.id %}" method='post'>

    {% csrf_token %}
    {{ form.as_p }}

    <button name="submit">Add Topping</button>
</form>

{% endblock content %}

Pizza_final/pizzas/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}


{% block content %}

<p> Pizza: {{ pizza.name }} </p>

<ul>
    {% for topping in toppings %}
    <li>
        <p>{{topping.name | linebreaks}}</p>
    </li>
    <p>
        <a href="{% url 'pizzas:edit_topping' topping.id %}">Edit Topping</a>
    </p>
    {% empty %}
    <li>Toppings for this pizza have not been added yet</li>
    {% endfor %}
</ul>

<p> <a href="{% url 'pizzas:new_topping' pizza.id %}">Add a new Topping</a> </p>

{% endblock content %}

Pizza_final/pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}


{% block content %}

<p> Pizzas </p>

<ul>
    {% for pizza in pizzas %}

    <li>
        <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
    </li>
    {% empty %}
    <li> No pizzas have been added yet.</li>

    {% endfor %}
</ul>

<a href="{% url 'pizzas:new_pizza' %}">Add a new Pizza</a>

{% endblock content %}